language: elixir
elixir:
  - 1.8
  - 1.9
otp_release:
  - 21.0
  - 22.0
script:
  - mix test --trace --cover
  - MIX_ENV=test mix credo
  - if [[ `elixir -v` = *"1.8"* ]]; then mix format --check-formatted; fi
  - cd test/integration
  - mix deps.get
  - mix test --no-start --trace --only integration
services:
  - redis-server
sudo: false
